print 'Insert Countries'
GO 

SET IDENTITY_INSERT Countries ON

INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (1, N'BG', N'БЪЛГАРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (2, N'AA', N'БЕЗ ГРАЖДАНСТВО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (3, N'AD', N'АНДОРА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (4, N'AE', N'ОБЕДИНЕНИ АРАБСКИ ЕМИРСТВА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (5, N'AF', N'АФГАНИСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (6, N'AG', N'АНТИГУА И БАРБУДА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (7, N'AI', N'АНГУИЛА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (8, N'AL', N'АЛБАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (9, N'AM', N'АРМЕНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (10, N'AN', N'НИДЕРЛАНДСКИ АНТИЛИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (11, N'AO', N'АНГОЛА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (12, N'AQ', N'АНТАРКТИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (13, N'AR', N'АРЖЕНТИНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (14, N'AS', N'ИЗТОЧНИ САМОА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (15, N'AT', N'АВСТРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (16, N'AU', N'АВСТРАЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (17, N'AW', N'АРУБА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (18, N'AZ', N'АЗЕРБАЙДЖАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (19, N'BA', N'БОСНА И ХЕРЦЕГОВИНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (20, N'BB', N'БАРБЕЙДОС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (21, N'BD', N'БАНГЛАДЕШ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (22, N'BE', N'БЕЛГИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (23, N'BF', N'БУРКИНА ФАСО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (24, N'BH', N'БАХРЕЙН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (25, N'BI', N'БУРУНДИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (26, N'BJ', N'БЕНИН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (27, N'BM', N'БЕРМУДСКИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (28, N'BN', N'БРУНЕЙ ДАРУССАЛАМ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (29, N'BO', N'БОЛИВИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (30, N'BR', N'БРАЗИЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (31, N'BS', N'БАХАМСКИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (32, N'BT', N'БУТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (33, N'BU', N'БИРМА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (34, N'BW', N'БОТСУАНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (35, N'BY', N'БЕЛАРУС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (36, N'BZ', N'БЕЛИЗ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (37, N'CA', N'КАНАДА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (38, N'CC', N'КОКОСОВИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (39, N'CE', N'ЧСФР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (40, N'CF', N'ЦЕНТРАЛНОАФРИКАНСКА РЕПУБЛИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (41, N'CG', N'КОНГО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (42, N'CH', N'ШВЕЙЦАРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (43, N'CI', N'КОТ Д''ИВОАР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (44, N'CK', N'КУК(О-ВИ)', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (45, N'CL', N'ЧИЛИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (46, N'CM', N'КАМЕРУН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (47, N'CN', N'КИТАЙ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (48, N'CO', N'КОЛУМБИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (49, N'CR', N'КОСТА РИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (50, N'CS', N'СЪРБИЯ И ЧЕРНА ГОРА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (51, N'CU', N'КУБА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (52, N'CV', N'КАБО ВЕРДЕ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (53, N'CX', N'РОЖДЕСТВО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (54, N'CY', N'КИПЪР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (55, N'CZ', N'ЧЕШКА РЕПУБЛИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (56, N'DE', N'ГЕРМАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (57, N'DJ', N'ДЖИБУТИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (58, N'DK', N'ДАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (59, N'DM', N'ДОМИНИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (60, N'DO', N'ДОМИНИКАНСКА РЕПУБЛИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (61, N'DZ', N'АЛЖИР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (62, N'EC', N'ЕКВАДОР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (63, N'EE', N'ЕСТОНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (64, N'EG', N'ЕГИПЕТ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (65, N'EH', N'ЗАПАДНА САХАРА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (66, N'ER', N'ЕРИТРЕЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (67, N'ES', N'ИСПАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (68, N'ET', N'ЕТИОПИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (69, N'FI', N'ФИНЛАНДИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (70, N'FJ', N'ФИДЖИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (71, N'FK', N'ФОЛКЛЕНДСКИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (72, N'FM', N'МИКРОНЕЗИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (73, N'FO', N'ФЕРЬОРСКИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (74, N'FR', N'ФРАНЦИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (75, N'FX', N'ФРАНЦИЯ,МЕТРОПОЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (76, N'GA', N'ГАБОН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (77, N'GB', N'ВЕЛИКОБРИТАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (78, N'GD', N'ГРЕНАДА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (79, N'GE', N'ГРУЗИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (80, N'GF', N'ФРЕНСКА ГВИАНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (81, N'GH', N'ГАНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (82, N'GI', N'ГИБРАЛТАР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (83, N'GL', N'ГРЕНЛАНДИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (84, N'GM', N'ГАМБИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (85, N'GN', N'ГВИНЕЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (86, N'GP', N'ГВАДЕЛУПА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (87, N'GQ', N'ЕКАТОРИАЛНА ГВИНЕЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (88, N'GR', N'ГЪРЦИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (89, N'GS', N'ЮЖНА ДЖОРДЖИЯ И ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (90, N'GT', N'ГВАТЕМАЛА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (91, N'GU', N'ГУАМ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (92, N'GW', N'ГВИНЕЯ-БИСАУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (93, N'GY', N'ГАЯНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (94, N'HK', N'ХОНКОНГ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (95, N'HM', N'ХЪРД И МАКДОНАЛД О-ВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (96, N'HN', N'ХОНДУРАС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (97, N'HR', N'ХЪРВАТСКО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (98, N'HT', N'ХАИТИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (99, N'HU', N'УНГАРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (100, N'ID', N'ИНДОНЕЗИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (101, N'IE', N'ИРЛАНДИЯ (ЕЙРЕ)', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (102, N'IL', N'ИЗРАЕЛ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (103, N'IN', N'ИНДИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (104, N'IO', N'БРИТАН.ТЕР.В ИНДИЙСКИЯ О-Н', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (105, N'IQ', N'ИРАК', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (106, N'IR', N'ИРАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (107, N'IS', N'ИСЛАНДИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (108, N'IT', N'ИТАЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (109, N'JM', N'ЯМАЙКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (110, N'JO', N'ЙОРДАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (111, N'JP', N'ЯПОНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (112, N'KE', N'КЕНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (113, N'KG', N'КИРГИЗСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (114, N'KH', N'КАМБОДЖА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (115, N'KI', N'КИРИБАТИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (116, N'KM', N'КОМОРСКИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (117, N'KN', N'СЕЙНТ КИТС И НЕЙВИС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (118, N'KP', N'КОРЕЯ (ДЕМОКРАТИЧНА НР)', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (119, N'KR', N'КОРЕЯ (РЕПУБЛИКА)', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (120, N'KW', N'КУВЕЙТ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (121, N'KY', N'КАЙМАНОВИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (122, N'KZ', N'КАЗАХСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (123, N'LA', N'ЛАОС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (124, N'LB', N'ЛИВАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (125, N'LC', N'СЕЙНТ ЛУСИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (126, N'LI', N'ЛИХТЕНЩАЙ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (127, N'LK', N'ШРИ ЛАНКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (128, N'LR', N'ЛИБЕРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (129, N'LS', N'ЛЕСОТО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (130, N'LT', N'ЛИТВА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (131, N'LU', N'ЛЮКСЕМБУРГ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (132, N'LV', N'ЛАТВИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (133, N'LY', N'ЛИБИЙСКА АРАБСКА ДЖАМАХИРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (134, N'MA', N'МАРОКО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (135, N'MC', N'МОНАКО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (136, N'MD', N'МОЛДОВА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (137, N'MG', N'МАДАГАСКАР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (138, N'MH', N'МАРШАЛСКИ ОСТРОВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (139, N'MI', N'МИДУЕЙ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (140, N'MK', N'МАКЕДОНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (141, N'ML', N'МАЛИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (142, N'MM', N'МИАНМА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (143, N'MN', N'МОНГОЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (144, N'MO', N'МАКАО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (145, N'MP', N'СЕВ.МАРИАНСКИ О-ВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (146, N'MQ', N'МАРТИНИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (147, N'MR', N'МАВРИТАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (148, N'MS', N'МОНТСЕРАТ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (149, N'MT', N'МАЛТА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (150, N'MU', N'МАВРИЦИЙ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (151, N'MV', N'МАЛДИВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (152, N'MW', N'МАЛАВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (153, N'MX', N'МЕКСИКО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (154, N'MY', N'МАЛАЙЗИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (155, N'MZ', N'МОЗАМБИК', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (156, N'NA', N'НАМИБИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (157, N'NC', N'НОВА КАЛЕДОНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (158, N'NE', N'НИГЕР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (159, N'NF', N'НОРФОЛК', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (160, N'NG', N'НИГЕРИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (161, N'NI', N'НИКАРАГУА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (162, N'NL', N'НИДЕРЛАНДИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (163, N'NO', N'НОРВЕГИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (164, N'NP', N'НЕПАЛ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (165, N'NR', N'НАУРУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (166, N'NU', N'НИУЕ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (167, N'NZ', N'НОВА ЗЕЛАНДИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (168, N'OM', N'ОМАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (169, N'PA', N'ПАНАМА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (170, N'PE', N'ПЕРУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (171, N'PF', N'ФРЕНСКА ПОЛИНЕЗИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (172, N'PG', N'ПАПУА-НОВА ГВИНЕЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (173, N'PH', N'ФИЛИПИНИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (174, N'PK', N'ПАКИСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (175, N'PL', N'ПОЛША', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (176, N'PM', N'СЕН ПИЕР И МИКЕЛОН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (177, N'PN', N'ПИТКЕЪРН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (178, N'PR', N'ПУЕРТО РИКО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (179, N'PS', N'ПАЛЕСТИНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (180, N'PT', N'ПОРТУГАЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (181, N'PU', N'БЕЙКЕР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (182, N'PW', N'ПАЛАУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (183, N'PY', N'ПАРАГВАЙ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (184, N'QA', N'КАТАР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (185, N'RE', N'РЕЮНИОН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (186, N'RO', N'РУМЪНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (187, N'RU', N'РУСКА ФЕДЕРАЦИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (188, N'RW', N'РУАНДА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (189, N'SA', N'САУДИТСКА АРАБИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (190, N'SB', N'СОЛОМОНОВИ О-ВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (191, N'SC', N'СЕЙШЕЛИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (192, N'SD', N'СУДАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (193, N'SE', N'ШВЕЦИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (194, N'SG', N'СИНГАПУР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (195, N'SH', N'СВЕТА ЕЛЕНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (196, N'SI', N'СЛОВЕНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (197, N'SJ', N'СВАЛБАР И ЯН МАЙЕН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (198, N'SK', N'СЛОВАКИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (199, N'SL', N'СИЕРА ЛЕОНЕ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (200, N'SM', N'САН МАРИНО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (201, N'SN', N'СЕНЕГАЛ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (202, N'SO', N'СОМАЛИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (203, N'SR', N'СУРИНАМ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (204, N'ST', N'САО ТОМЕ И ПРИНСИПИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (205, N'SU', N'СССР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (206, N'SV', N'САЛВАДОР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (207, N'SY', N'СИРИЙСКА АРАБСКА РЕПУБЛИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (208, N'SZ', N'СУАЗИЛЕНД', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (209, N'TC', N'ТЪРКС И КАЙКОС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (210, N'TD', N'ЧАД', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (211, N'TF', N'ФРЕНСКИ ЮЖНИ ТЕРИТОРИИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (212, N'TG', N'ТОГО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (213, N'TH', N'ТАЙЛАНД', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (214, N'TJ', N'ТАДЖИКИСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (215, N'TK', N'ТОКЕЛАУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (216, N'TM', N'ТУРКМЕНИСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (217, N'TN', N'ТУНИС', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (218, N'TO', N'ТОНГА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (219, N'TP', N'ИЗТОЧЕН ТИМОР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (220, N'TR', N'ТУРЦИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (221, N'TT', N'ТРИНИДАД И ТОБАГО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (222, N'TV', N'ТУВАЛУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (223, N'TW', N'ТАЙВАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (224, N'TZ', N'ТАНЗАНИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (225, N'UA', N'УКРАЙНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (226, N'UG', N'УГАНДА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (227, N'UM', N'МАЛКИ О-ВИ ПРИНАД.НА САЩ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (228, N'US', N'САЩ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (229, N'UY', N'УРУГВАЙ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (230, N'UZ', N'УЗБЕКИСТАН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (231, N'VA', N'ВАТИКАНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (232, N'VC', N'СЕЙНТ ВИНСЕНТ И ГРЕНАДИНИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (233, N'VE', N'ВЕНЕЦУЕЛА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (234, N'VG', N'ВИРДЖИНСКИ О-ВИ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (235, N'VI', N'ВИРДЖИНСКИ О-ВИ (САЩ)', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (236, N'VN', N'ВИЕТНАМ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (237, N'VU', N'ВАНУАТУ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (238, N'WF', N'УОЛИС И ФУТУНА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (239, N'WS', N'САМОА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (240, N'YE', N'ЙЕМЕН', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (241, N'YT', N'МАЙОТ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (242, N'YU', N'ЮГОСЛАВИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (243, N'ZA', N'ЮЖНА АФРИКА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (244, N'ZM', N'ЗАМБИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (245, N'ZR', N'ЗАИР', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (246, N'ZW', N'ЗИМБАБВЕ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (247, N'ZX', N'НЕПОКАЗАНО', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (248, N'ME', N'ЧЕРНА ГОРА', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (249, N'RS', N'СЪРБИЯ', 1)
INSERT INTO Countries(CountryId, Code, Name, IsActive) VALUES (250, N'XK', N'КОСОВО', 1)


SET IDENTITY_INSERT Countries OFF
GO 
