print 'Insert Municipalities'
GO 

SET IDENTITY_INSERT Municipalities ON

INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(1,2,N'BGS01',N'Айтос',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(2,2,N'BGS04',N'Бургас',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(3,2,N'BGS06',N'Средец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(4,2,N'BGS08',N'Камено',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(5,2,N'BGS09',N'Карнобат',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(6,2,N'BGS12',N'Малко Търново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(7,2,N'BGS13',N'Царево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(8,2,N'BGS15',N'Несебър',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(9,2,N'BGS17',N'Поморие',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(10,2,N'BGS18',N'Руен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(11,2,N'BGS21',N'Созопол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(12,2,N'BGS23',N'Сунгурларе',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(13,2,N'BGS27',N'Приморско',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(14,1,N'BLG01',N'Банско',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(15,1,N'BLG02',N'Белица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(16,1,N'BLG03',N'Благоевград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(17,1,N'BLG11',N'Гоце Делчев',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(18,1,N'BLG13',N'Гърмен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(19,1,N'BLG28',N'Кресна',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(20,1,N'BLG33',N'Петрич',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(21,1,N'BLG37',N'Разлог',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(22,1,N'BLG40',N'Сандански',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(23,1,N'BLG42',N'Сатовча',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(24,1,N'BLG44',N'Симитли',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(25,1,N'BLG49',N'Струмяни',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(26,1,N'BLG52',N'Хаджидимово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(27,1,N'BLG53',N'Якоруда',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(28,8,N'DOB03',N'Балчик',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(29,8,N'DOB12',N'Генерал Тошево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(30,8,N'DOB15',N'Добрич-селска',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(31,8,N'DOB17',N'Каварна',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(32,8,N'DOB20',N'Крушари',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(33,8,N'DOB27',N'Тервел',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(34,8,N'DOB28',N'Добрич',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(35,8,N'DOB29',N'Шабла',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(36,7,N'GAB05',N'Габрово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(37,7,N'GAB12',N'Дряново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(38,7,N'GAB29',N'Севлиево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(39,7,N'GAB35',N'Трявна',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(40,26,N'HKV09',N'Димитровград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(41,26,N'HKV11',N'Ивайловград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(42,26,N'HKV17',N'Любимец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(43,26,N'HKV18',N'Маджарово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(44,26,N'HKV19',N'Минерални бани',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(45,26,N'HKV28',N'Свиленград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(46,26,N'HKV29',N'Симеоновград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(47,26,N'HKV30',N'Стамболово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(48,26,N'HKV32',N'Тополовград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(49,26,N'HKV33',N'Харманли',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(50,26,N'HKV34',N'Хасково',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(51,28,N'JAM03',N'Болярово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(52,28,N'JAM07',N'Елхово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(53,28,N'JAM22',N'Стралджа',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(54,28,N'JAM25',N'Тунджа',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(55,28,N'JAM26',N'Ямбол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(56,10,N'KNL04',N'Бобов дол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(57,10,N'KNL05',N'Бобошево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(58,10,N'KNL27',N'Кочериново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(59,10,N'KNL29',N'Кюстендил',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(60,10,N'KNL31',N'Невестино',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(61,10,N'KNL38',N'Рила',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(62,10,N'KNL41',N'Сапарева баня',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(63,10,N'KNL48',N'Дупница',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(64,10,N'KNL50',N'Трекляно',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(65,9,N'KRZ02',N'Ардино',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(66,9,N'KRZ08',N'Джебел',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(67,9,N'KRZ14',N'Кирково',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(68,9,N'KRZ15',N'Крумовград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(69,9,N'KRZ16',N'Кърджали',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(70,9,N'KRZ21',N'Момчилград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(71,9,N'KRZ35',N'Черноочене',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(72,11,N'LOV02',N'Априлци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(73,11,N'LOV17',N'Летница',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(74,11,N'LOV18',N'Ловеч',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(75,11,N'LOV19',N'Луковит',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(76,11,N'LOV33',N'Тетевен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(77,11,N'LOV34',N'Троян',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(78,11,N'LOV36',N'Угърчин',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(79,11,N'LOV38',N'Ябланица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(80,12,N'MON02',N'Берковица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(81,12,N'MON04',N'Бойчиновци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(82,12,N'MON07',N'Брусарци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(83,12,N'MON11',N'Вълчедръм',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(84,12,N'MON12',N'Вършец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(85,12,N'MON14',N'Георги Дамяново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(86,12,N'MON24',N'Лом',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(87,12,N'MON26',N'Медковец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(88,12,N'MON29',N'Монтана',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(89,12,N'MON36',N'Чипровци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(90,12,N'MON38',N'Якимово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(91,13,N'PAZ03',N'Батак',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(92,13,N'PAZ04',N'Белово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(93,13,N'PAZ06',N'Брацигово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(94,13,N'PAZ08',N'Велинград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(95,13,N'PAZ14',N'Лесичово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(96,13,N'PAZ19',N'Пазарджик',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(97,13,N'PAZ20',N'Панагюрище',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(98,13,N'PAZ21',N'Пещера',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(99,13,N'PAZ24',N'Ракитово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(100,13,N'PAZ29',N'Септември',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(101,13,N'PAZ32',N'Стрелча',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(102,16,N'PDV01',N'Асеновград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(103,16,N'PDV07',N'Брезово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(104,16,N'PDV12',N'Калояново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(105,16,N'PDV13',N'Карлово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(106,16,N'PDV15',N'Лъки',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(107,16,N'PDV17',N'Марица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(108,16,N'PDV22',N'Пловдив',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(109,16,N'PDV23',N'Първомай',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(110,16,N'PDV25',N'Раковски',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(111,16,N'PDV26',N'Родопи',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(112,16,N'PDV28',N'Садово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(113,16,N'PDV33',N'Съединение',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(114,16,N'PDV37',N'Хисаря',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(115,16,N'PDV39',N'Кричим',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(116,16,N'PDV40',N'Перущица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(117,16,N'PDV41',N'Стамболийски',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(118,16,N'PDV42',N'Куклен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(119,16,N'PDV43',N'Сопот',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(120,14,N'PER08',N'Брезник',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(121,14,N'PER19',N'Земен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(122,14,N'PER22',N'Ковачевци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(123,14,N'PER32',N'Перник',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(124,14,N'PER36',N'Радомир',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(125,14,N'PER51',N'Трън',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(126,15,N'PVN03',N'Белене',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(127,15,N'PVN08',N'Гулянци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(128,15,N'PVN10',N'Долна Митрополия',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(129,15,N'PVN11',N'Долни Дъбник',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(130,15,N'PVN16',N'Левски',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(131,15,N'PVN21',N'Никопол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(132,15,N'PVN23',N'Искър',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(133,15,N'PVN24',N'Плевен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(134,15,N'PVN27',N'Пордим',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(135,15,N'PVN37',N'Червен бряг',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(136,15,N'PVN39',N'Кнежа',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(137,17,N'RAZ11',N'Завет',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(138,17,N'RAZ14',N'Исперих',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(139,17,N'RAZ16',N'Кубрат',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(140,17,N'RAZ17',N'Лозница',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(141,17,N'RAZ26',N'Разград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(142,17,N'RAZ29',N'Самуил',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(143,17,N'RAZ36',N'Цар Калоян',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(144,18,N'RSE03',N'Борово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(145,18,N'RSE04',N'Бяла',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(146,18,N'RSE05',N'Ветово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(147,18,N'RSE08',N'Две могили',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(148,18,N'RSE13',N'Иваново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(149,18,N'RSE27',N'Русе',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(150,18,N'RSE33',N'Сливо поле',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(151,18,N'RSE37',N'Ценово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(152,23,N'SFO06',N'Божурище',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(153,23,N'SFO07',N'Ботевград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(154,23,N'SFO09',N'Годеч',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(155,23,N'SFO10',N'Горна Малина',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(156,23,N'SFO16',N'Драгоман',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(157,23,N'SFO17',N'Елин Пелин',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(158,23,N'SFO18',N'Етрополе',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(159,23,N'SFO20',N'Ихтиман',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(160,23,N'SFO24',N'Копривщица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(161,23,N'SFO25',N'Костенец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(162,23,N'SFO26',N'Костинброд',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(163,23,N'SFO34',N'Правец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(164,23,N'SFO39',N'Самоков',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(165,23,N'SFO43',N'Своге',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(166,23,N'SFO45',N'Сливница',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(167,23,N'SFO47',N'Златица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(168,23,N'SFO54',N'Антон',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(169,23,N'SFO55',N'Пирдоп',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(170,23,N'SFO56',N'Мирково',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(171,23,N'SFO57',N'Чавдар',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(172,23,N'SFO58',N'Челопеч',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(173,23,N'SFO59',N'Долна баня',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(174,27,N'SHU07',N'Венец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(175,27,N'SHU10',N'Върбица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(176,27,N'SHU11',N'Хитрино',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(177,27,N'SHU18',N'Каолиново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(178,27,N'SHU19',N'Каспичан',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(179,27,N'SHU21',N'Никола Козлево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(180,27,N'SHU22',N'Нови пазар',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(181,27,N'SHU23',N'Велики Преслав',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(182,27,N'SHU25',N'Смядово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(183,27,N'SHU30',N'Шумен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(184,19,N'SLS01',N'Алфатар',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(185,19,N'SLS07',N'Главиница',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(186,19,N'SLS10',N'Дулово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(187,19,N'SLS15',N'Кайнарджа',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(188,19,N'SLS31',N'Силистра',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(189,19,N'SLS32',N'Ситово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(190,19,N'SLS34',N'Тутракан',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(191,20,N'SLV11',N'Котел',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(192,20,N'SLV16',N'Нова Загора',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(193,20,N'SLV20',N'Сливен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(194,20,N'SLV24',N'Твърдица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(195,21,N'SML02',N'Баните',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(196,21,N'SML05',N'Борино',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(197,21,N'SML09',N'Девин',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(198,21,N'SML10',N'Доспат',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(199,21,N'SML11',N'Златоград',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(200,21,N'SML16',N'Мадан',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(201,21,N'SML18',N'Неделино',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(202,21,N'SML27',N'Рудозем',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(203,21,N'SML31',N'Смолян',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(204,21,N'SML38',N'Чепеларе',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(205,22,N'SOF46',N'Столична',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(206,24,N'SZR04',N'Братя Даскалови',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(207,24,N'SZR07',N'Гълъбово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(208,24,N'SZR12',N'Казанлък',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(209,24,N'SZR22',N'Мъглиж',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(210,24,N'SZR23',N'Опан',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(211,24,N'SZR24',N'Павел баня',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(212,24,N'SZR27',N'Раднево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(213,24,N'SZR31',N'Стара Загора',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(214,24,N'SZR36',N'Чирпан',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(215,24,N'SZR37',N'Гурково',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(216,24,N'SZR38',N'Николаево',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(217,25,N'TGV02',N'Антоново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(218,25,N'TGV22',N'Омуртаг',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(219,25,N'TGV23',N'Опака',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(220,25,N'TGV24',N'Попово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(221,25,N'TGV35',N'Търговище',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(222,3,N'VAR01',N'Аврен',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(223,3,N'VAR02',N'Аксаково',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(224,3,N'VAR04',N'Белослав',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(225,3,N'VAR05',N'Бяла',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(226,3,N'VAR06',N'Варна',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(227,3,N'VAR08',N'Ветрино',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(228,3,N'VAR09',N'Вълчи дол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(229,3,N'VAR13',N'Долни чифлик',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(230,3,N'VAR14',N'Девня',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(231,3,N'VAR16',N'Дългопол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(232,3,N'VAR24',N'Провадия',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(233,3,N'VAR26',N'Суворово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(234,5,N'VID01',N'Белоградчик',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(235,5,N'VID03',N'Бойница',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(236,5,N'VID06',N'Брегово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(237,5,N'VID09',N'Видин',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(238,5,N'VID15',N'Грамада',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(239,5,N'VID16',N'Димово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(240,5,N'VID22',N'Кула',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(241,5,N'VID25',N'Макреш',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(242,5,N'VID30',N'Ново село',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(243,5,N'VID33',N'Ружинци',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(244,5,N'VID37',N'Чупрене',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(245,6,N'VRC05',N'Борован',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(246,6,N'VRC08',N'Бяла Слатина',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(247,6,N'VRC10',N'Враца',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(249,6,N'VRC20',N'Козлодуй',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(250,6,N'VRC21',N'Криводол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(251,6,N'VRC27',N'Мездра',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(252,6,N'VRC28',N'Мизия',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(253,6,N'VRC31',N'Оряхово',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(254,6,N'VRC32',N'Роман',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(255,6,N'VRC35',N'Хайредин',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(256,4,N'VTR04',N'Велико Търново',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(257,4,N'VTR06',N'Горна Оряховица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(258,4,N'VTR13',N'Елена',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(259,4,N'VTR14',N'Златарица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(260,4,N'VTR20',N'Лясковец',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(261,4,N'VTR22',N'Павликени',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(262,4,N'VTR26',N'Полски Тръмбеш',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(263,4,N'VTR28',N'Свищов',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(264,4,N'VTR31',N'Стражица',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(265,4,N'VTR32',N'Сухиндол',NULL,NULL,1,DEFAULT)
INSERT INTO [Municipalities] ([MunicipalityId],[DistrictId],[Code],[Name],[Alias],[Description],[IsActive],[Version])VALUES(266,29,N'SYS99',N'*',NULL,NULL,1,DEFAULT)


SET IDENTITY_INSERT Municipalities OFF
