print 'Insert MusicTypes'
GO 

SET IDENTITY_INSERT Extras ON

INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(1,N'2 етажа',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(2,N'DJ',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(3,N'Wi Fi',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(4,N'автомивка',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(5,N'аквариум',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(6,N'басейн',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(7,N'бебешка стая (4м-4г)',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(8,N'безжичен интернет',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(9,N'билярд',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(10,N'вестници',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(11,N'видео охрана',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(12,N'ВИП зала',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(13,N'вход',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(14,N'гардероб',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(15,N'градина',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(16,N'грил маси',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(17,N'дансинг',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(18,N'дартс',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(19,N'детски кът',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(20,N'джаги',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(21,N'Джакузи',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(22,N'езикови консултации',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(23,N'живи цветя',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(24,N'закачалки',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(25,N'зарядно телефони',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(26,N'зен градина',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(27,N'зимна градина',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(28,N'игри на открито',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(29,N'камина',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(30,N'караоке',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(31,N'кетъринг',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(32,N'климатик',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(33,N'кулинарни консултации',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(34,N'лап танц',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(35,N'лимо момичета',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(36,N'микрофони',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(37,N'мултимедиа',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(38,N'наргиле',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(39,N'обедно меню',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(40,N'онлайн резервации',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(41,N'охрана',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(42,N'панорама',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(43,N'парти снимки',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(44,N'пиано',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(45,N'плейстейшън',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(46,N'програма',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(47,N'промоции',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(48,N'свещи, интимност',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(49,N'сейф',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(50,N'сепарета',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(51,N'снукър',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(52,N'собствен паркинг',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(53,N'стаг парти',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(54,N'стриптийз',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(55,N'стриптийз шоу',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(56,N'сцена',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(57,N'сценично осветление',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(58,N'татами рум',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(59,N'телевизор',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(60,N'тематични декори',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(61,N'тепаняки',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(62,N'тераса',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(63,N'фейс контрол',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(64,N'хотел',NULL,1)
INSERT INTO Extras(ExtraId,Name,Alias,IsActive)VALUES(65,N'шоу кухня',NULL,1)

SET IDENTITY_INSERT Extras OFF
GO 