print 'Insert MusicTypes'
GO 

SET IDENTITY_INSERT KitchenTypes ON

INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(1,N'авторска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(2,N'алкохол',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(3,N'американска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(4,N'рабска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(5,N'аржентинска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(6,N'аржентинска ',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(7,N'арменска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(8,N'балканска скара',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(9,N'био продукти',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(10,N'бразилска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(11,N'българска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(12,N'вегeтарианска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(13,N'гръцка',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(14,N'гурме',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(15,N'домашни птици',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(16,N'еврейска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(17,N'европейска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(18,N'индийска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(19,N'индонезийска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(20,N'интернационална',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(21,N'ирландска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(22,N'испанска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(23,N'италианска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(24,N'китайска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(25,N'коктейли',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(26,N'кубинска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(27,N'латино',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(28,N'ливанска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(29,N'мароканска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(30,N'мексиканска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(31,N'миди',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(32,N'наливна бира',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(33,N'немска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(34,N'прясна паста',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(35,N'риба и рибни специалитети',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(36,N'румънска ',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(37,N'руска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(38,N'скара, барбекю',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(39,N'средиземноморска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(40,N'сръбска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(41,N'студена кухня',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(42,N'суши',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(43,N'тай кухня',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(44,N'турска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(45,N'унгарска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(46,N'френска',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(47,N'черноморска риба',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(48,N'чешка',NULL,1)
INSERT INTO KitchenTypes(KitchenTypeId,Name,Alias,IsActive)VALUES(49,N'японска',NULL,1)

SET IDENTITY_INSERT KitchenTypes OFF
GO 