print 'Insert MusicTypes'
GO 

SET IDENTITY_INSERT MusicTypes ON

INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(1,N'dance',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(2,N'deep house',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(3,N'DJ',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(4,N'drum and bass',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(5,N'funky house',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(6,N'gothic',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(7,N'industrial',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(8,N'lounge',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(9,N'progressive house',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(10,N'R&B',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(11,N'rock & metal',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(12,N'арабска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(13,N'БГРадио',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(14,N'българска народна',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(15,N'българска поп',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(16,N'гръцка',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(17,N'джаз',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(18,N'диско',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(19,N'евъргрийн',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(20,N'електронна ',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(21,N'етно',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(22,N'индийска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(23,N'ирландска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(24,N'испанска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(25,N'италианска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(26,N'караоке',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(27,N'класическа',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(28,N'кънтри',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(29,N'латино',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(30,N'мексиканска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(31,N'музика на живо',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(32,N'ориенталска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(33,N'пиано',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(34,N'поп',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(35,N'поп фолк',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(36,N'реге',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(37,N'ретро',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(38,N'рок',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(39,N'рокстеди',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(40,N'руска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(41,N'силна музика',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(42,N'ска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(43,N'соул',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(44,N'сръбска музика',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(45,N'тех хаус',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(46,N'транс',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(47,N'турска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(48,N'френска',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(49,N'фънк',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(50,N'фънки',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(51,N'фънки хаус',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(52,N'хаус',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(53,N'хип-хоп',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(54,N'чил аут',NULL,1)
INSERT INTO MusicTypes(MusicTypeId,Name,Alias,IsActive)VALUES(55,N'японска',NULL,1)

SET IDENTITY_INSERT MusicTypes OFF
GO 