print 'Insert Noms'
GO 

SET IDENTITY_INSERT Noms ON

INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (1,1,N'ресторант',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (2,1,N'нощен клуб',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (3,1,N'механа',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (4,1,N'бар',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (5,1,N'кафе',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (6,1,N'bar & dinner',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (7,1,N'пицария',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (8,1,N'айриш пъб',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (9,1,N'билярд клуб',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (10,1,N'бирария',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (11,1,N'бистро',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (12,1,N'бързо хранене',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (13,1,N'винарна',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (14,1,N'вино бар',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (15,1,N'денонощно',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (16,1,N'детски клуб',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (17,1,N'дискотека',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (18,1,N'еротичен клуб',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (19,1,N'индийски ресторант',NULL,1 )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (20,1,N'концерт / liveshow',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (21,1,N'кръчма',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (22,1,N'наргиле бар',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (23,1,N'пиано бар',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (24,1,N'пъб',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (25,1,N'рибен ресторант',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (26,1,N'сладкарница',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (27,1,N'суши бар',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (28,1,N'таверна',NULL,1  )
INSERT INTO Noms(NomId,NomTypeId, Name, Alias, IsActive) VALUES (29,1,N'фолк клуб',NULL,1  )

INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(30,2,N'авторска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(31,2,N'алкохол',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(32,2,N'американска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(33,2,N'рабска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(34,2,N'аржентинска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(35,2,N'аржентинска ',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(36,2,N'арменска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(37,2,N'балканска скара',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(38,2,N'био продукти',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(39,2,N'бразилска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(40,2,N'българска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(41,2,N'вегeтарианска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(42,2,N'гръцка',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(43,2,N'гурме',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(44,2,N'домашни птици',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(45,2,N'еврейска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(46,2,N'европейска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(47,2,N'индийска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(48,2,N'индонезийска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(49,2,N'интернационална',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(50,2,N'ирландска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(51,2,N'испанска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(52,2,N'италианска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(53,2,N'китайска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(54,2,N'коктейли',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(55,2,N'кубинска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(56,2,N'латино',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(57,2,N'ливанска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(58,2,N'мароканска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(59,2,N'мексиканска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(60,2,N'миди',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(61,2,N'наливна бира',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(62,2,N'немска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(63,2,N'прясна паста',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(64,2,N'риба и рибни специалитети',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(65,2,N'румънска ',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(66,2,N'руска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(67,2,N'скара, барбекю',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(68,2,N'средиземноморска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(69,2,N'сръбска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(70,2,N'студена кухня',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(71,2,N'суши',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(72,2,N'тай кухня',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(73,2,N'турска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(74,2,N'унгарска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(75,2,N'френска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(76,2,N'черноморска риба',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(77,2,N'чешка',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(78,2,N'японска',NULL,1)

INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(79,3,N'dance',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(80,3,N'deep house',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(81,3,N'DJ',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(82,3,N'drum and bass',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(83,3,N'funky house',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(84,3,N'gothic',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(85,3,N'industrial',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(86,3,N'lounge',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(87,3,N'progressive house',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(88,3,N'R&B',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(89,3,N'rock & metal',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(90,3,N'арабска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(91,3,N'БГРадио',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(92,3,N'българска народна',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(93,3,N'българска поп',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(94,3,N'гръцка',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(95,3,N'джаз',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(96,3,N'диско',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(97,3,N'евъргрийн',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(98,3,N'електронна ',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(99,3,N'етно',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(100,3,N'индийска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(101,3,N'ирландска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(102,3,N'испанска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(103,3,N'италианска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(104,3,N'караоке',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(105,3,N'класическа',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(106,3,N'кънтри',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(107,3,N'латино',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(108,3,N'мексиканска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(109,3,N'музика на живо',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(110,3,N'ориенталска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(111,3,N'пиано',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(112,3,N'поп',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(113,3,N'поп фолк',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(114,3,N'реге',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(115,3,N'ретро',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(116,3,N'рок',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(117,3,N'рокстеди',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(118,3,N'руска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(119,3,N'силна музика',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(120,3,N'ска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(121,3,N'соул',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(122,3,N'сръбска музика',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(123,3,N'тех хаус',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(124,3,N'транс',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(125,3,N'турска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(126,3,N'френска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(127,3,N'фънк',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(128,3,N'фънки',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(129,3,N'фънки хаус',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(130,3,N'хаус',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(131,3,N'хип-хоп',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(132,3,N'чил аут',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(133,3,N'японска',NULL,1)

INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(134,4,N'абитуриентски балове',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(135,4,N'банкети',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(136,4,N'бизнес среща',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(137,4,N'вегетарианци',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(138,4,N'гледане на мач',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(139,4,N'детско парти',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(140,4,N'деца',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(141,4,N'еротичен масаж',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(142,4,N'закуска',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(143,4,N'имени дни',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(144,4,N'коктейли',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(145,4,N'коледни партита',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(146,4,N'малки концерти',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(147,4,N'напиване',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(148,4,N'непушачи',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(149,4,N'обилно наяждане',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(150,4,N'обяд',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(151,4,N'официално облекло',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(152,4,N'първа среща с гадже',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(153,4,N'ревюта',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(154,4,N'рождени дни',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(155,4,N'романтика',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(156,4,N'сватби',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(157,4,N'семейна среща',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(158,4,N'среща с приятели',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(159,4,N'тийм билдинг',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(160,4,N'тържества',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(161,4,N'фирмени партита',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(162,4,N'частни партита',NULL,1)

INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(163,5,N'2 етажа',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(164,5,N'DJ',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(165,5,N'Wi Fi',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(166,5,N'автомивка',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(167,5,N'аквариум',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(168,5,N'басейн',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(169,5,N'бебешка стая (4м-4г)',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(170,5,N'безжичен интернет',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(171,5,N'билярд',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(172,5,N'вестници',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(173,5,N'видео охрана',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(174,5,N'ВИП зала',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(175,5,N'вход',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(176,5,N'гардероб',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(177,5,N'градина',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(178,5,N'грил маси',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(179,5,N'дансинг',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(180,5,N'дартс',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(181,5,N'детски кът',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(182,5,N'джаги',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(183,5,N'Джакузи',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(184,5,N'езикови консултации',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(185,5,N'живи цветя',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(186,5,N'закачалки',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(187,5,N'зарядно телефони',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(188,5,N'зен градина',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(189,5,N'зимна градина',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(190,5,N'игри на открито',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(191,5,N'камина',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(192,5,N'караоке',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(193,5,N'кетъринг',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(194,5,N'климатик',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(195,5,N'кулинарни консултации',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(196,5,N'лап танц',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(197,5,N'лимо момичета',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(198,5,N'микрофони',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(199,5,N'мултимедиа',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(200,5,N'наргиле',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(201,5,N'обедно меню',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(202,5,N'онлайн резервации',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(203,5,N'охрана',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(204,5,N'панорама',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(205,5,N'парти снимки',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(206,5,N'пиано',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(207,5,N'плейстейшън',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(208,5,N'програма',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(209,5,N'промоции',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(210,5,N'свещи, интимност',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(211,5,N'сейф',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(212,5,N'сепарета',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(213,5,N'снукър',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(214,5,N'собствен паркинг',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(215,5,N'стаг парти',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(216,5,N'стриптийз',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(217,5,N'стриптийз шоу',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(218,5,N'сцена',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(219,5,N'сценично осветление',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(220,5,N'татами рум',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(221,5,N'телевизор',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(222,5,N'тематични декори',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(223,5,N'тепаняки',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(224,5,N'тераса',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(225,5,N'фейс контрол',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(226,5,N'хотел',NULL,1)
INSERT INTO Noms(NomId,NomTypeId,Name,Alias,IsActive)VALUES(227,5,N'шоу кухня',NULL,1)

SET IDENTITY_INSERT Noms OFF